export const defaultConfig = {
    selectedValue: [],
    showCustomList: [],
    omitSelected: false,
    expandChip: false,
    error: false,
    helperText : "",
    buttonContent : "Save Selected",
    trailing: true,
    leading: true,
    leading: true,
    trailingIcon: true,
    selectedValue: [],
    selectLimit: -1,
    inputClass: "NSI-input-box",
    dropDownClass: "NSI-select-drop-down-menu-wrapper",
    buttonClass: "NSI-select-drop-down-menu-button",
    width: 360,
    enableButton: true,
    disabled: false,
    state: true,
    continent: true,
    onChipDelet: (value) => {},
    onViewmore: (value) => {},
    callback : (value) => {},
    onChange: (value) => {}, // only when enableButton : false
    onSearch: (s_sting) => {},
    ...props
}